name: build and deploy

env:
  ARTIFACT_NAME: LambdaFunction.zip
  AWS_REGION: us-east-1
  CODEDEPLOY_APPLICATION_NAME: DemoLambda
  CODEDEPLOY_APPLICATION_DEVELOPMENT_GROUP: DemoGroup

on: 
  push:
    branches:
    - main

jobs: 

  ci-cd:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x ]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Creating Lambda Artifact File
      run: |
        npm install
        zip -r ${{env.ARTIFACT_NAME}} index.js package.json mail.js appspec.yml
        mkdir artifact
        ls -al
        mv ${{env.ARTIFACT_NAME}} artifact/
     
    - name: Configuring AWS S3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Copy Artifact to s3
      run: |
        aws s3 sync ./artifact s3://${{secrets.CODEDEPLOY_Lambda_BUCKET}}
    
    - name: CodeDeploy 
      run: |
        output=$(aws lambda  update-function-code \
        --function-name demo \
        --zip-file fileb://artifact/${{env.ARTIFACT_NAME}} \
        --publish
        )
          echo $output